
import Footer from "@/components/Footer";
import "./globals.css";

import { Roboto } from 'next/font/google';
import Header from "@/components/Header";

const roboto = Roboto({
  subsets: ['latin'], // Ensures Latin characters are included
  weight: ['400', '700'], // Specify weights like normal (400) and bold (700)
  variable: '--font-roboto', // CSS variable for custom usage
});

export const metadata = {
  title: "Car Rental",
  description: "Generated by  AZ Sheeno",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className}   antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
